!FINDING MEAN,MEDIAN AND STANDARD DEVIATION

PROGRAM MEAN_MEDIAN_SD
 IMPLICIT NONE
 REAL::DAT(100),VAR(100),SIGMA_SQ=0,SIGMA,MEAN,MEDIAN,SD,DAT_SUM=0
 INTEGER::N,I,J

 PRINT*,"HOW MANY DATA YOU HAVE"
  READ*,N
 PRINT*,"ENTER THE DATA"
  DO I=1,N
    READ*,DAT(I)
    DAT_SUM=DAT_SUM+DAT(I)
  END DO
 IF(MOD(N,2) == 0 ) THEN
  J=N/2
  MEDIAN=DAT(J)
 ELSE
  J=N/2
  MEDIAN=(DAT(J)+DAT(J+1))/2
 ENDIF

  MEAN=DAT_SUM/N
DO I=1,N
 VAR(I)=MEAN-DAT(I)
 SIGMA_SQ=SIGMA_SQ+VAR(I)**2
END DO
SIGMA_SQ=SIGMA_SQ/(N-1)
SIGMA=SQRT(REAL(SIGMA_SQ))

PRINT*,"MEAN=",MEAN,";","MEDIAN=",MEDIAN,";","STANDARD DEVIATION=",SIGMA
END PROGRAM MEAN_MEDIAN_SD
 
